name: Feature Request 🚀
description: Request a new feature, improvement, or general suggestion
title: "[Feature] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following information to help us understand your request.
        > [!warning]
        > Only use English. Any other languages will be deleted.
  - type: dropdown
    id: device_type
    attributes:
      label: Device
      description: "Which device type is this feature for?"
      options:
        - All devices
        - Phone/Tablet
        - Desktop
        - TV
      multiple: false
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: "Suggestion"
      description: "What do you want to suggest?"
    validations:
      required: true
